"""add renovation and year_built to properties

Revision ID: cf4a36e717b9
Revises: 002
Create Date: 2026-06-23 13:50:51.613797

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cf4a36e717b9'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('renovation', sa.String(length=100), nullable=True))
    op.add_column('properties', sa.Column('year_built', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'year_built')
    op.drop_column('properties', 'renovation')
    # ### end Alembic commands ###
